# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1705794e977f36a81e5ebc75dcb4a2a27a54ac7377f8d842aa40637859e13c84b46cfaee92269fbcdaffc21f23388a49cc56696646cbe8640c6e2f56929dca28

test:
  secret_key_base: 7b5776335a101047de7b26a1355e333a93bea4dae65a9600470ea451b13a6b94d7cdc772d111e8630b95501953f8c9e0d0784c6b06df4a00d41b7cbc9f2bf984

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
